config/routes.rb
Spabooker::Application.routes.draw do

  
  

  resources :manage_leaves do
    member do
      put :update_status
    end

    collection do
      delete 'delete_selected'
    end
  end

  get "payments/index"

  get "hr_system/index"

  resources :payments do
    member do
      get "update_service_packages"
      put :update_status
    end

    collection do
      get "cash_register"
      post "new_entry"
      get 'search_cash_register'
    end

  end
  resources :gift_vouchers

    

  resources :sub_categories

  resources :payments

  resources :categories do
    member do
      post "add_sub_category"
      delete "delete_sub_category"
      get 'get_sub_categories'
    end
  end

  resources :services do
    member do
      get 'update_service_rates'
      delete "delete_selected_option"
    end

    collection do
      delete 'delete_selected'
      post "search"
    end
  end

  

  root :to => "guests#index"
  get "users/new"

 
  resources :appointments do
    collection do
      get 'appointments_by_date'
    end

    collection do
      get 'calendar'
      post "search"
    end

    member do
      get 'invoice'
      get 'print_invoice'
      post 'appointment_payment'
    end

  end

  resources :guests do
    member do
      put :update_status
      put :update_custom_field
      delete :destroy_custom_field
      get :appointments
      get :notes
      post :create_note
      delete :delete_note
      put :update_field
      get :purchases
    end
    collection do
      delete 'delete_selected'
      post 'csv_import'
      get 'csv_guest_form'
      get 'search'
      get :export_to_xls
      get :export_to_csv
      get :export_pdf
      get 'filter_guest'
      get :custom_fields
      post :create_custom_field
      post :change_custom_field_name
      post :change_custom_field_type
      get 'get_empty_csv'
      get 'guest_custom_field'
      
    end
  end

  resources  :events do
    member do
      post 'resize'
      post 'move'
    end

    collection do
      get 'get_events'
    end
  end

  resources :roles do
    collection do
      delete 'delete_selected'
      get 'search'
    
    end

    member do
      put :update_status
      put 'assign_permission'
    end
  end

  resources :permissions

  resources :user_sessions

  resources :users do
    collection do
      get 'manage_role'
      get 'new_user'
      post 'create_user'
    end

  
    member do
      put :update_name
    end
  end
  
  resources :packages do
    member do
      put :update_status
   
    end
    collection do
      delete 'delete_selected'
      post 'search'
    end
  end

  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  resources :locations do
    collection do
      delete 'delete_selected'
      post 'search'
      get 'get_outlets'
    end
    member do
      put :update_status
      get :get_operation_hours
      post :create_operation_hours
      get :show_operation_hours_on_date
      put :update_operation_time
      get :closed_dates
      get :new_closed_date
      post :add_closed_date
      get :edit_closed_date
      put :update_closed_date
      delete :delete_closed_date
    end
  end

  resources :equipments do
    collection do
      delete 'delete_selected'
      post 'search'
      put 'update_location_equipment_status'
    end
    member do
      put :update_status
    end
  end

  resources :employees do
    resources :leave_applications
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put "update_status"
      get :assign_role
    end
  end

  resources :rooms do
    collection do
      delete 'delete_selected'
      post 'search'
      
    end
    member do
      put :update_status
    end
  end

  resources :taxtypes do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    end
  end

  resources :memberships do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    end

  end

  resources :products do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    
      get "update_sub_categorie_products"
    end
    resources :inventories
  end

  resources :profiles do

    collection do
      delete 'delete_selected'
      post 'csv_import'
      get 'csv_profile_form'
      get :export_to_csv
      get :export_to_xls
      get :export_pdf
      post 'search'
      get 'get_empty_csv'
    end
    member do
      put :update_status
    end
  end

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'signup' => "users#new", :as=>:signup
  match 'account' => "users#account", :as=>:account
  match 'activate/:activation_code' => "users#activate", :as =>:activate

  
  

end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :service_name, :category_id, :sub_category_id, :duration, :staff_recovery_time, :room_recovery_time, :book_online, :rate,:equipment,:special_notes, :status, :service_code, :requires_equipment
  attr_accessor :service_ids, :room_ids, :equipment_ids, :service_id, :employee_id, :room_id, :equipment_id
  belongs_to :category
  belongs_to :sub_category
  has_many :appointments
  has_many :membership_services, :dependent => :destroy
  has_many :memberships , :through => :membership_services

  has_many :package_services, :dependent => :destroy
  has_many :packages, :through => :package_services


  has_many :payment_services, :dependent => :destroy
  has_many :payments, :through => :payment_services

  has_many :room_services, :dependent => :destroy
  has_many :rooms, :through => :room_services

  has_many :employee_services, :dependent => :destroy
  has_many :employees, :through => :employee_services


  has_many :equipments_services, :dependent => :destroy
  has_many :equipments, :through => :equipments_services

  has_many :products_services, :dependent => :destroy
  has_many :products, :through => :products_services
  
  define_index do
    indexes service_name, :sortable => true
    indexes duration, :sortable => true
    indexes rate, :sortable => true
    indexes status, :sortable => true
  end

  

  validates :service_name, :category_id, :sub_category_id, :duration, :book_online, :status, :service_code , :presence => true
  validates_length_of :service_name, :maximum => 200
  validates_length_of :rate, :maximum => 10
  validates_length_of :special_notes, :maximum => 250, :allow_blank => true
  validates_numericality_of :rate
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :is_admin
  
  def index
    per_page = params[:per_page] || 10
    params[:order] = params[:order] || 'service_name'
    params[:by] = params[:by] || 'ASC'
    @services = Service.paginate(:all, :conditions => ["status !='Deleted'"], :page => params[:page], :per_page => per_page, :order => params[:order]+' '+params[:by])
  end

  def search
    per_page = params[:per_page] || 10
    @service_ids = []
    if !params[:name].to_s.blank?
      @service = Service.search_for_ids "*#{params[:name]}*"
      @service_ids << @service if !@service.empty?
    end
    if !params[:rate].to_s.blank?
      @service = Service.search_for_ids "*#{params[:rate]}*"
      @service_ids << @service if !@service.empty?
    end
    if !params[:duration].to_s.blank?
      @service = Service.search_for_ids "*#{params[:duration]}*"
      @service_ids << @service if !@service.empty?
    end
    if !params[:status].to_s.blank? and !params[:ststus] == "None"
      @service = Service.search_for_ids "*#{params[:status]}*"
      @service_ids << @service if !@service.empty?
    end
    @services = Service.find(@service_ids)
    @services = @services.delete_if{|service| service.status != params[:status]}
    @services = @services.paginate(:page => params[:page], :per_page=> per_page )
    render :action => 'index'
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
    @categories = Category.all
    @sub_categories = SubCategory.all
  end

  def create
    @service = Service.new(params[:service])
    @service.status = 'Active'
    if @service.save
      if params[:applied_to_employee] == '1' and !params[:service][:employee_ids].empty?
        params[:service][:employee_ids].each do |employee_id|
          EmployeesService.create(:employee_id => employee_id, :service_id => @service.id)
        end
      end
      if params[:applied_to_room] == '1' and !params[:service][:room_ids].empty?
        params[:service][:room_ids].each do |room_id|
          RoomService.create(:room_id => room_id, :service_id => @service.id)
        end
      end
      if params[:service][:requires_equipment] == '1' and !params[:service][:equipment_ids].empty?
        params[:service][:equipment_ids].each do |equipment_id|
          EquipmentsService.create(:equipment_id => equipment_id, :service_id => @service.id)
        end
      end
      @products = Product.all
      if !@products.empty?
        @products.each do |product|
          if params[:"#{product.id}_selected"] == '1'
            ProductsService.create(:product_id => product.id, :service_id => @service.id, :quantity => params[:"#{product.id}_quantity"], :product_cost => params[:"#{product.id}_amount"])
          end
        end
      end
      flash[:notice] = "Successfully created service."
      redirect_to services_path
    else
      flash.now[:error] = "Couldn't create the new service, plase try again."
      @categories = Category.all
      @sub_categories = SubCategory.all
      render :action => 'new'
    end
  end

  def edit
    @service = Service.find(params[:id])
    @categories = Category.all
    @sub_categories = SubCategory.all
  end

  def update
    @service = Service.find(params[:id])
    if @service.update_attributes(params[:service])
      flash[:notice] = "Successfully updated service."
      redirect_to services_path
    else
      @categories = Category.all
      @sub_categories = SubCategory.all
      render :action => 'edit'
    end
  end

  def delete_selected
    if !params[:service_ids].to_a.empty?
      for service_id in params[:service_ids]
        Service.find(service_id).update_attribute(:status, 'Deleted')
      end
      flash[:notice] = "Succcessfully deleted selected services."
    else
      flash[:error] = "Please select atleast one service to delete"
    end
    redirect_to services_path
  end

  def destroy
    puts "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
    #    puts params[:services]
    #    @service = Service.find(params[:id])
    #    @service.destroy
    #    redirect_to services_url, :notice => "Successfully destroyed service."
  end

  def update_service_rates
    @service = Service.find(params[:id])
    options = "<input type='text' id='package_total_price' name='package[total_price]' value=#{@service.rate} size='30'"
    render :text => options
  end

  def delete_selected_option
    @service = Service.find(params[:id])
    if params[:delete_type] == 'Employee'
      @employee_service = EmployeesService.first(:conditions => ["service_id = ? and employee_id = ?",@service.id, params[:delete_id]])
      if @employee_service and @employee_service.destroy
        render :update do |page|
          page.replace_html 'assigned_employees', :partial => 'assigned_employees'
        end
      else
        render :update do |page|
          page.replace_html 'delete_message', "<span style='color:red'>Couldn't delete employee, please try again</span>"
        end
      end
    elsif params[:delete_type] == 'Room'
      @room_service = RoomService.first(:conditions => ["service_id = ? and room_id = ?",@service.id, params[:delete_id]])
      if @room_service and @room_service.destroy
        render :update do |page|
          page.replace_html 'assigned_rooms', :partial => 'assigned_rooms'
        end
      else
        render :update do |page|
          page.replace_html 'delete_message', "<span style='color:red'>Couldn't delete room, please try again</span>"
        end
      end
    elsif params[:delete_type] == 'Product'
      @product_service = ProductsService.find(params[:delete_id])
      if @product_service and @product_service.destroy
        render :update do |page|
          page.replace_html 'assigned_products', :partial => 'assigned_products'
        end
      else
        render :update do |page|
          page.replace_html 'delete_message', "<span style='color:red'>Couldn't delete product, please try again</span>"
        end
      end
    elsif params[:delete_type] == 'Equipment'
      @equipment_service = EquipmentsService.first(:conditions => ["service_id = ? and equipment_id = ? ",@service.id, params[:delete_id]])
      if @equipment_service and @equipment_service.destroy
        render :update do |page|
          page.replace_html 'assigned_equipments', :partial => 'assigned_equipments'
        end
      else
        render :update do |page|
          page.replace_html 'delete_message', "<span style='color:red'>Couldn't delete equipment, please try again</span>"
        end
      end
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_assigned_employees.html.erb
<table>
  <tr>
    <td colspan="2">
      <b style="font-size: medium; color: #1DACB2"> Assigned Employees</b>
      <% assigned_employees = @service.employees %>
    </td>
  </tr>
  <% if assigned_employees.empty? %>
    <tr>
      <td colspan="2">
        No employees are assigned to this service.
      </td>
    </tr>
  <% else %>
    <% assigned_employees.each do |emp| %>
      <tr>
        <td><%= emp.name %></td>
        <td><%= link_to 'Delete', delete_selected_option_service_path(@service.id, :delete_id => emp.id, :delete_type => 'Employee'), :remote => true, :method => 'delete', :confirm => "Are you sure?", :style => "color: salmon"  %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/services/_assigned_equipments.html.erb
<table>
  <tr>
    <td colspan="4">
      <br /><br />
      <b style="font-size: medium; color: #1DACB2"> Assigned Equipments</b>
      <% assigned_equipments = @service.equipments %>
    </td>
  </tr>
  <% if assigned_equipments.empty? %>
    <tr>
      <td colspan="4">
        No equipments have been used to this service.
      </td>
    </tr>
  <% else %>
    <% assigned_equipments.each do |equipment| %>
      <tr>
        <td><%= equipment.name %></td>
        <td><%= link_to 'Delete', delete_selected_option_service_path(@service.id, :delete_id => equipment.id, :delete_type => 'Equipment'), :remote => true, :method => 'delete', :confirm => "Are you sure?", :style => "color: salmon"  %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/services/_assigned_products.html.erb
<table>
  <tr>
    <td colspan="4">
      <br /><br />
      <b style="font-size: medium; color: #1DACB2"> Assigned Products</b>
      <% assigned_products = @service.products_services %>
    </td>
  </tr>
  <% if assigned_products.empty? %>
    <tr>
      <td colspan="4">
        No products have been used to this service.
      </td>
    </tr>
  <% else %>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Cost</th>
      <th></th>
    </tr>
    <% assigned_products.each do |product| %>
      <tr>
        <td><%= product.product.nil? ? 'Name Unknown' : product.product.name %></td>
        <td><%= product.quantity %></td>
        <td>$<%= product.product_cost %></td>
        <td><%= link_to 'Delete', delete_selected_option_service_path(@service.id, :delete_id => product.id, :delete_type => 'Product'), :remote => true, :method => 'delete', :confirm => "Are you sure?", :style => "color: salmon"  %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/services/_assigned_rooms.html.erb
<table>
  <tr>
    <td colspan="2"><br /><br />
      <b style="font-size: medium; color: #1DACB2"> Assigned Rooms</b>
      <% assigned_rooms = @service.rooms %>
    </td>
  </tr>
  <% if assigned_rooms.empty? %>
    <tr>
      <td colspan="2">
        No rooms are assigned to this service.
      </td>
    </tr>
  <% else %>
    <% assigned_rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= link_to 'Delete', delete_selected_option_service_path(@service.id, :delete_id => room.id, :delete_type => 'Room'), :remote => true, :method => 'delete', :confirm => "Are you sure?", :style => "color: salmon" %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/services/edit.html.erb
<%= render 'form' %>

app/views/services/index.html.erb
<div class="contentmiddle">
  <div class="leftcontentgradient"></div>
  <div class="centercontentgradient">
    <div id="guestmain">
      <%= render 'shared/service_sub_tab' %>
      <div class="midbgrepeat">
        <div class="midbgleft"></div>
        <div class="midcontent">
          <%= render "/shared/side_bar" %>
          <div class="midright">
            <div class="midrighttop">
              <div class="midrighttopleft"></div>
              <div class="midrighttopcenter">
                <div class="midrighttoplinks">
                  <div style="float:right">
                    <div class="midrighttoplinkdiv">
                      <%= link_to "New Service", new_service_path,  :class => 'midrighttoplink'%>
                    </div>
                    <div class="midrighttoplinkdiv">
                      <%= link_to 'Manage Categories', categories_path, :class => 'midrighttoplink' %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="midrighttopright"></div>
            </div>

            <div class="dataheaddiv" style="width:850px; text-align: left; border: 0; font-weight: bold;" >
              Search Criteria
            </div>
            <div class="search_tab_right">
              <%= form_tag(search_services_path, :method=>'post') do %>
                <table>
                  <tr>
                    <td>Service name : <%= text_field_tag "name", params[:name], :size => '20' %></td>
                    <td>Rate range : <%= text_field_tag "phone", params[:phone], :size => '15' %></td>
                    <td>Time required range : <%= text_field_tag "email", params[:email], :size => '15' %></td>
                  </tr>
                  <tr>
                    <td colspan="2">Status : <%= select_tag :status,  options_for_select(["None", "Active" ,"Inactive"],params[:status])  %>
                      Records per page : <%= select_tag :records_per_page,  options_for_select([10, 20, 30, 50],params[:records_per_page])  %></td>
                    <td >    <%= submit_tag 'Search', :class => "input_button"%></td>
                  </tr>
                </table>

              <%end%>
            </div>

            <%= form_tag  delete_selected_taxtypes_path, :method => :delete do %>
              <div class="data" >
                <div class="datahead">
                  <div class="dataheaddiv" style="width: 100%; text-align: left; border: 0">
                    <%= select_tag :per_page, options_for_select([10, 20, 30, 50], params[:per_page]), :onchange => "reload_with_new_param('per_page', this.value)"  %>
                  </div>

                </div>
                <div class="datahead">
                  <div class="dataheadoptions">
                    <input type="checkbox" id="total_services" onclick="select_all_services(<%= @services.length %>)"/>
                  </div>
                  <div class="dataheaddiv" style="width:110px; padding-left: 2px">
                    Service Name
                    <% if params[:by] == 'ASC' %>
                      <%= link_to image_tag("uparrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'service_name', :by => 'DESC' %>
                    <% else %>
                      <%= link_to image_tag("arrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'service_name', :by => 'ASC' %>
                    <% end %>
                  </div>
                  <div class="dataheaddiv" style="width:90px" >
                    Category
                  </div>
                  <div class="dataheaddiv" style="width:120px">
                    Sub Category
                  </div>

                  <div class="dataheaddiv" style="width:100px">
                    Duration
                  </div>
                  <div class="dataheaddiv" style="width:170px">
                    Staff Recovery Time
                  </div>
                  <div class="dataheaddiv" style="width:90px">
                    Price
                    <% if params[:by] == 'ASC' %>
                      <%= link_to image_tag("uparrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'rate', :by => 'DESC' %>
                    <% else %>
                      <%= link_to image_tag("arrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'rate', :by => 'ASC' %>
                    <% end %>
                  </div>
                  <div class="dataheaddiv" style="width:106px">
                    Status
                  </div>
                </div>
                <% i = 0 %>
                <% for service in @services %>
                  <div class="datahead" style="background-color: <%= cycle("#cce9ed","#f0f8fa") %>">
                    <div class="datarowoptions">
                      <input type="checkbox" name="service_ids[]" id="service_<%= i %>" value="<%= service.id %>"/>
                    </div>
                    <div class="dataheaddivwhite" style="width:110px; padding-left: 3px">
                      <%= link_to  "#{service.service_name}", service_path(service.id) %>
                    </div>
                    <div class="databellowdiv" style="width:90px">
                      <%= service.category.nil? ? "Unknown " : service.category.name %>
                    </div>
                    <div class="dataheaddivwhite" style="width:120px; padding-left: 2px">
                      <%=  service.sub_category.nil? ? "Unknown" : service.sub_category.name %>
                    </div>
                    <div class="dataheaddivwhite" style="width:100px">
                      <%= service.duration.nil? ? "Unknown" : service.duration.strftime("%a, %B %d, at %l:%M %p") %>
                    </div>
                    <div class="dataheaddivwhite" style="width:170px; padding-left: 3px">
                      <%= service.staff_recovery_time.nil? ? "Unknown" : service.staff_recovery_time.strftime("%a, %B %d,  at %l:%M %p") %>
                    </div>
                    <div class="dataheaddivwhite" style="width:90px; padding-left: 3px">
                      $<%= service.rate.nil? ? "Unknown" : service.rate  %>
                    </div>
                    <div class="databellowdiv" style="width:106px">
                      <%= service.status.nil? ? "Unknown" : service.status %>
                    </div>
                  </div>
                  <% i += 1 %>
                <% end %>
              </div>
              <div style="clear: both; height: 10px"></div>
              <div class="pagination">
                <%= will_paginate @services  %>
              </div>
              <div style="clear: both; height: 10px"></div>
              <%= submit_tag 'Delete', :onclick => "return validate_services_to_delete(#{@services.length})", :class => 'input_button' %>
            <% end %>
          </div>
        </div>
        <div class="midbgright"></div>
      </div>
    </div>
  </div>
  <div class="rightcontentgradient"></div>
</div>

app/views/services/new.html.erb
<%= render 'form' %>

app/views/services/show.html.erb
<div class="contentmiddle">
  <div class="leftcontentgradient"></div>
  <div class="centercontentgradient">
    <div id="guestmain">
      <%= render 'shared/service_sub_tab' %>
      <div class="midbgrepeat">
        <div class="midbgleft"></div>
        <div class="midcontent">
          <%= render '/shared/side_bar' %>
          <div class="midright">
            <table>
              <tr>
                <td>
                  Service Name: </td>
                <td>
                  <%=@service.service_name.nil? ? "Unknown" : @service.service_name%>
                </td>
              </tr >
              <td>
                Category :</td>
              <td> <%=@service.category.nil? ? "Unknown" : @service.category.name%>
              </td>
              <tr>
                <td>
                  Sub Category: </td>
                <td><%= @service.sub_category.nil? ? "Unknown" : @service.sub_category.name %>
                </td>
              </tr>
              <tr>
                <td>
                  Duration :</td>
                <td> <%= @service.duration.nil? ? "Unknown" : @service.duration.strftime("%l hr %M mins ") %>
                </td>
              </tr>
              <tr>
                <td>
                  Staff Recovery Time:</td>
                <td>   <%= @service.staff_recovery_time.nil? ? "Unknown" :  @service.staff_recovery_time.strftime("%l hr %M mins") %>
                </td>
              </tr>
              <tr>
                <td>
                  Room Recovery Time : </td>
                <td> <%= @service.room_recovery_time.nil? ? "Unknown" : @service.room_recovery_time.strftime("%l hr %M mins") %>
                </td>
              </tr>
              <tr>
                <td>
                  Status :
                </td>
                <td>
                  <%= @service.status.nil? ? "Unknown" : @service.status%>
                </td>
              </tr>
            </table>
            <table>
              <tr>
                <td>
                  <div class="dataheaddiv" style="width:500px; text-align: center; padding-left: 50px">
                    <b style="font-size: 15px;">Additional Options</b>
                  </div>
                </td>
              </tr>
            </table>
            <div id="delete_message"></div>
            <div id="assigned_employees">
              <%= render 'assigned_employees' %>
            </div>
            <div id="assigned_rooms">
              <%= render 'assigned_rooms' %>
            </div>
            <div id="assigned_products">
              <%= render 'assigned_products' %>
            </div>
            <div id="assigned_equipments">
              <%= render 'assigned_equipments' %>
            </div>
            <table>
              <tr>
                <td>
                </td>
                <td>
                  <%= button_to_function 'Edit' ,  "window.location.href= '#{edit_service_path(@service.id)}'", :class => 'input_button' %>
                  <%= button_to_function 'Back', "window.location.href= '#{services_path}'", :class => 'input_button' %>
                </td>
              </tr>
            </table>
          </div>
        </div>
        <div class="midbgright"></div>
      </div>
    </div>
  </div>
  <div class="rightcontentgradient"></div>
</div>