config/routes.rb
Spabooker::Application.routes.draw do

  
  

  resources :manage_leaves do
    member do
      put :update_status
    end

    collection do
      delete 'delete_selected'
    end
  end

  get "payments/index"

  get "hr_system/index"

  resources :payments do
    member do
      get "update_service_packages"
      put :update_status
    end

    collection do
      get "cash_register"
      post "new_entry"
      get 'search_cash_register'
    end

  end
  resources :gift_vouchers

    

  resources :sub_categories

  resources :payments

  resources :categories do
    member do
      post "add_sub_category"
      delete "delete_sub_category"
      get 'get_sub_categories'
    end
  end

  resources :services do
    member do
      get 'update_service_rates'
      delete "delete_selected_option"
    end

    collection do
      delete 'delete_selected'
      post "search"
    end
  end

  

  root :to => "guests#index"
  get "users/new"

 
  resources :appointments do
    collection do
      get 'appointments_by_date'
    end

    collection do
      get 'calendar'
      post "search"
    end

    member do
      get 'invoice'
      get 'print_invoice'
      post 'appointment_payment'
    end

  end

  resources :guests do
    member do
      put :update_status
      put :update_custom_field
      delete :destroy_custom_field
      get :appointments
      get :notes
      post :create_note
      delete :delete_note
      put :update_field
      get :purchases
    end
    collection do
      delete 'delete_selected'
      post 'csv_import'
      get 'csv_guest_form'
      get 'search'
      get :export_to_xls
      get :export_to_csv
      get :export_pdf
      get 'filter_guest'
      get :custom_fields
      post :create_custom_field
      post :change_custom_field_name
      post :change_custom_field_type
      get 'get_empty_csv'
      get 'guest_custom_field'
      
    end
  end

  resources  :events do
    member do
      post 'resize'
      post 'move'
    end

    collection do
      get 'get_events'
    end
  end

  resources :roles do
    collection do
      delete 'delete_selected'
      get 'search'
    
    end

    member do
      put :update_status
      put 'assign_permission'
    end
  end

  resources :permissions

  resources :user_sessions

  resources :users do
    collection do
      get 'manage_role'
      get 'new_user'
      post 'create_user'
    end

  
    member do
      put :update_name
    end
  end
  
  resources :packages do
    member do
      put :update_status
   
    end
    collection do
      delete 'delete_selected'
      post 'search'
    end
  end

  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  resources :locations do
    collection do
      delete 'delete_selected'
      post 'search'
      get 'get_outlets'
    end
    member do
      put :update_status
      get :get_operation_hours
      post :create_operation_hours
      get :show_operation_hours_on_date
      put :update_operation_time
      get :closed_dates
      get :new_closed_date
      post :add_closed_date
      get :edit_closed_date
      put :update_closed_date
      delete :delete_closed_date
    end
  end

  resources :equipments do
    collection do
      delete 'delete_selected'
      post 'search'
      put 'update_location_equipment_status'
    end
    member do
      put :update_status
    end
  end

  resources :employees do
    resources :leave_applications
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put "update_status"
      get :assign_role
    end
  end

  resources :rooms do
    collection do
      delete 'delete_selected'
      post 'search'
      
    end
    member do
      put :update_status
    end
  end

  resources :taxtypes do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    end
  end

  resources :memberships do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    end

  end

  resources :products do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    
      get "update_sub_categorie_products"
    end
    resources :inventories
  end

  resources :profiles do

    collection do
      delete 'delete_selected'
      post 'csv_import'
      get 'csv_profile_form'
      get :export_to_csv
      get :export_to_xls
      get :export_pdf
      post 'search'
      get 'get_empty_csv'
    end
    member do
      put :update_status
    end
  end

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'signup' => "users#new", :as=>:signup
  match 'account' => "users#account", :as=>:account
  match 'activate/:activation_code' => "users#activate", :as =>:activate

  
  

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  require 'country_select'
  attr_accessor :location_ids, :service_ids
  has_attached_file :avatar,
    :default_url => "/images/default_avatar.jpg",
    :url =>  "/system/employee/:id/:style/:basename.:extension",
    :path => ":rails_root/public/system/employee/:id/:style/:basename.:extension",
    :styles => {
    :thumb=> "100x200>",
    :medium => "100x100>",
    :large => "300x400>"
  }
  validates_attachment_size :avatar, :less_than => 2.megabytes

  #  has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "100x100>" }
  #  validates_attachment_size :avatar, :less_than => 2.megabytes
  validates :name, :email, :gender, :status, :address1, :address2, :street, :city, :pin_code, :phone1, :date_of_birth, :presence => true
  validates :name,:email, :uniqueness => true

  #  has_many :employee_roles
  #  has_many :roles, :through => :employee_roles
  has_many :employee_locations, :dependent => :destroy
  has_many :locations , :through => :employee_locations
  has_many :leave_applications, :dependent => :destroy
  belongs_to :employee_type, :foreign_key =>'employee_type_id'
  has_one :user
  has_many :payments
  has_many :appointments, :dependent => :destroy
  has_many :guests

  has_many :employee_services, :dependent => :destroy
  has_many :services, :through => :employee_services

  define_index do
    indexes name, :sortable => true
    #    indexes location, :sortable => true
  end
  #

#  def validate
#    #  errors.add :country, "You must select a state" if country == 'None'
#    if location_ids.to_a.empty?
#      errors.add :location_ids, "Please select atleast one location"
#    end
#
#  end

  #

  def assign_roles(role_ids)
    selected_roles = !role_ids.to_a.empty? ? Role.find(:all, :conditions => ["id IN (#{role_ids.to_a.uniq.join(', ')})"]) : []
    self.employee_roles.each do |e_l|
      if selected_roles.map{|l| l.id}.include?(e_l.role_id)
        selected_roles.delete_if{|sl| sl.id == e_l.role_id}
      else
        self.employee_roles.delete(e_l)
      end
    end
    self.roles << selected_roles
  end
end    

app/models/employee_type.rb
class EmployeeType < ActiveRecord::Base
  has_many :employees, :foreign_key =>'employee_type_id'
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "100x100>" }

  validates :status, :name, :sales_tax, :presence => true
  validates :category_id, :presence => { :message => "Please slect one category"}
  validates :sub_category_id, :presence => { :message => "Please slect one sub category"}
  validates :name, :uniqueness => true
  validates :sales_tax, :quantity, :numericality => true

  has_many :payment_products, :dependent => :destroy
  has_many :payments, :through => :payment_products
  
  has_many :inventories, :dependent => :destroy
  belongs_to :category, :foreign_key => 'category_id'
  belongs_to :sub_category, :foreign_key => 'sub_category_id'
  belongs_to :product_brand, :foreign_key => 'product_brand_id'

  has_many :products_services, :dependent => :destroy
  has_many :services, :through => :products_services

  has_many :locations_products, :dependent => :destroy
  has_many :locations, :through => :locations_products


  define_index do
    indexes name, :sortable => true
    indexes status, :status => true
    #    indexes location, :sortable => true
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :has_permission?, :only => [:index, :show, :new, :create, :edit, :update, :destroy]

  def search
    per_page = params[:per_page] || 10
    @employee_ids = []
    if !params[:name].to_s.blank?
      @employee = Employee.search_for_ids "*#{params[:name]}*"
      @employee_ids << @employee if !@employee.empty?
    end
    if !@employee_ids.to_s.blank?
      @employees = Employee.find(@employee_ids).paginate(:page => params[:page], :per_page => per_page)
    else
      flash[:error] = "Couldn't find any employees with the search criteria."
      @employees = [].paginate
    end
    render 'index'
  end

  def index
    per_page = params[:per_page] || 10
    params[:order] = params[:order] || 'name'
    params[:by] = params[:by] || 'ASC'
    @employees = Employee.paginate(:all, :conditions => ["status !='Deleted'"], :page => params[:page], :per_page => per_page, :order => params[:order]+' '+params[:by])
  end

  def update_status
    @employee = Employee.find(params[:id])
    if @employee and @employee.update_attributes(:status => params[:status])
      message = "<span style='color: green'>Updated</span>"
    else
      message = "<span style='color: red'>Error</span>"
    end
    render :text => message 
  end

  def delete_selected
    if !params[:employee_ids].to_a.empty?
      for employee_id in params[:employee_ids]
        Employee.find(employee_id).update_attribute(:status, 'Deleted')
      end
    else
      flash[:error] = "Please select atleast one employee to delete"
    end
    redirect_to employees_path
  end

  def show
    @employee = Employee.find(params[:id])
    @leave_applications = @employee.leave_applications
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(params[:employee])
    @employee.status = 'Active'
    if @employee.save

      if  !params[:employee][:location_ids].empty?
        params[:employee][:location_ids].each do |location_id|
          EmployeeLocation.create(:location_id => location_id, :employee_id => @employee.id)
        end
      end

      if !params[:employee][:service_ids].empty?
        params[:employee][:service_ids].each do |service_id|
          EmployeeService.create(:employee_id => @employee.id, :service_id => service_id)
        end
      end
     
      flash[:notice] = "Successfully created employee with name #{@employee.name}."
      redirect_to employees_path
    else
      flash.now[:error] = "Couldn't create employee, please try again."
      render :action => 'new'
    end
  end
 
  def assign_role
    @roles = Role.find(:all)
  end

  def edit
    @employee = Employee.find(params[:id])
    @leave_applications = @employee.leave_applications
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      flash[:notice] = "Successfully updated employee details with name #{@employee.name}."
      redirect_to employees_path
    else
      flash.now[:error] = "Couldn't update employee, please try again."
      render :action => "edit"
    end
  end

  def destroy
    if @employee = Employee.destroy(params[:id])
      flash[:notice] = "Successfully deleted employee."
    else
      flash[:error] = "Couldn't delete employee, please try again."
    end
    redirect_to employees_path
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
 
end

app/views/employees/_form.html.erb
<div class="contentmiddle">
  <div class="leftcontentgradient"></div>
  <div class="centercontentgradient">
    <div id="guestmain">
      <%= render 'shared/employee_sub_tab' %>
      <div class="midbgrepeat">
        <div class="midbgleft"></div>
        <div class="midcontent">
          <%= render "/shared/side_bar" %>
          <div class="midright">
            <%= form_for @employee, :html => { :multipart => true } do |f| %>
              <h3 style="color:#FFFFFF; padding-left:5%">New Employee</h3>
              <table style="padding-left: 5%">
                <tr>
                  <td> Employee Name</td>
                  <td><%= f.text_field :name  %>
                    <div style='color: red;'><%= validation_errors @employee.errors['name'] %></div>
                  </td>
                </tr>

                <tr>
                  <td> Email</td>
                  <td><%= f.text_field :email  %>
                    <div style='color: red;'><%= validation_errors @employee.errors['email'] %></div>
                  </td>
                </tr>

                <tr>
                  <td>Gender</td>
                  <td><%= f.radio_button :gender, "Male" %>Male<%= f.radio_button :gender, "Female" %>Female<div style='color: red;'><%= validation_errors @employee.errors['gender'] %></div></td>
                </tr>
                <tr>
                  <td>Employee Type</td>
                  <% @employee_types = EmployeeType.all %>
                  <td><%= f.select :employee_type_id, [["Select", " "]]+EmployeeType.all(:select => "employee_type, id").map{|r| [r.employee_type,r.id]} %></td>
                </tr>
                <tr>
                  <td>Location Outlet</td>
                  <td>
                    <%= f.select :location_ids, options_for_select(Location.all(:select => "name, id").map {|r| [r.name,r.id] }, (params[:employee] ? params[:employee][:location_ids] : @employee.locations.all(:select => "locations.id").map{|l| [l.id]})), {}, {:multiple => true, :size => 6, :style => 'min-width:100px'} %>
                  </td>
                </tr>
                <tr>
                  <td>Services</td>
                  <td>
                    <%= f.select :service_ids, options_for_select(Service.all(:select => "service_name, id").map {|r| [r.service_name,r.id] }, (params[:employee] ? params[:employee][:service_ids] : @employee.services.all(:select => "services.id").map{|l| [l.id]})), {}, {:multiple => true, :size => 6, :style => 'min-width:100px'} %>
                  </td>
                </tr>
                <tr>
                  <td>Address1</td>
                  <td><%= f.text_field :address1  %>
                    <div style='color: red;'><%= validation_errors @employee.errors['address1'] %></div>
                  </td>
                </tr>

                <tr>
                  <td>Address2</td>
                  <td><%= f.text_field :address2  %>
                    <div style='color: red;'><%= validation_errors @employee.errors['address2'] %></div>
                  </td>
                </tr>
                <tr>
                  <td>Street</td>
                  <td><%= f.text_field :street  %>
                    <div style='color: red;'><%= validation_errors @employee.errors['street'] %></div>
                  </td>
                </tr>
                <tr>
                  <td>City</td>
                  <td><%= f.text_field :city  %>
                    <div style='color: red;'><%= validation_errors @employee.errors['city'] %></div>
                  </td>
                </tr>
                <tr>
                  <td>Country</td>
                  <td><%= f.country_select :country, ["Singapore"], {}, { :style => "width: 200px;"} %>
                    <div style='color: red;' ><%= validation_errors @employee.errors['country'] %></div>
                  </td>
                </tr>
                <tr>
                  <td>Pin Code</td>
                  <td><%= f.text_field :pin_code %>
                    <div style='color: red;'><%= validation_errors @employee.errors['pin_code'] %></div>
                  </td>
                </tr>
                <tr>
                  <td>Phone1</td>
                  <td><%= f.text_field :phone1 %>
                    <div style='color: red;'><%= validation_errors @employee.errors['phone1'] %></div>
                  </td>
                </tr>
                <tr>
                  <td>Phone2</td>
                  <td><%= f.text_field :phone2 %>
                    <div style='color: red;'><%= validation_errors @employee.errors['phone2'] %></div>
                  </td>
                </tr>
                <tr>
                  <td>Date of Birth</td>
                  <td><%= f.date_select :date_of_birth, :prompt => { :day => 'Day', :month => 'Month',:year => 'Year' }, :start_year => 1900 %></td>
                </tr>
                <tr>
                  <td>Photo</td>
                  <td><%= f.file_field :avatar %></td>
                </tr>
                <tr>
                  <td>Special Notes</td>
                  <td><%= f.text_area :notes,:size => '40x4' %>
                    <div style='color: red;' ><%= validation_errors @employee.errors['special_notes'] %></div>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td><%= f.submit @employee.new_record? ? "Create"  : "Update", :class => 'input_button' %>
                    <%= button_to_function 'Cancel', "window.location.href= '#{employees_path}'", :class => 'input_button' %>
                  </td>
                </tr>
              </table>
            <% end %>
          </div>
        </div>
        <div class="midbgright"></div>
      </div>
    </div>
  </div>
  <div class="rightcontentgradient"></div>
</div>

app/views/employees/edit.html.erb
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<div class="contentmiddle">
  <div class="leftcontentgradient"></div>
  <div class="centercontentgradient">
    <div id="guestmain">
      <%= render 'shared/employee_sub_tab' %>
      <div class="midbgrepeat">
        <div class="midbgleft"></div>
        <div class="midcontent">
          <%= render "/shared/side_bar" %>
          <div class="midright">
            <div class="midrighttop">
              <div class="midrighttopleft"></div>
              <div class="midrighttopcenter">
                <div class="midrighttoplinks">
                  <div style="float:right">
                    <div class="midrighttoplinkdiv">
                      <%= link_to "New Employee" , new_employee_path,  :class => 'midrighttoplink'%>
                    </div>
                  </div>
                </div>
              </div>
              <div class="midrighttopright"></div>
            </div>

            <div class="dataheaddiv" style="width:850px; text-align: left; border: 0; font-weight: bold;" >
              Search Criteria
            </div>
            <div class="search_tab_right">
              <%= form_tag(search_employees_path, :method=>'post', :multipart => true) do %>
                Name : <%= text_field_tag "name", params[:name] %>
                Status : <%= select_tag :status,  options_for_select(["Active" ,"Inactive"],params[:status])  %>
                <%= submit_tag 'Search', :class => "input_button"%>
              <%end%>
            </div>
            <%= form_tag delete_selected_employees_path, :method => :delete do %>
              <div class="data" >
                <div class="datahead">
                  <div class="dataheaddiv" style="width: 100%; text-align: left; border: 0">
                    <%= select_tag :per_page, options_for_select([10, 20, 30, 50], params[:per_page]), :onchange => "reload_with_new_param('per_page', this.value)"  %>
                  </div>

                </div>
                <div class="datahead">
                  <div class="dataheadoptions">
                    <input type="checkbox" id="total_employees" onclick="select_all_employees(<%= @employees.length %>)"/>
                  </div>
                  <div class="dataheaddiv" style="width:110px">
                    Name
                    <% if params[:by] == 'ASC' %>
                      <%= link_to image_tag("uparrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'name', :by => 'DESC' %>
                    <% else %>
                      <%= link_to image_tag("arrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'name', :by => 'ASC' %>
                    <% end %>
                  </div>

                  <div class="dataheaddiv" style="width:170px">
                    Services
                  </div>
                  <div class="dataheaddiv" style="width:170px" >
                    Email
                    <% if params[:by] == 'ASC' %>
                      <%= link_to image_tag("uparrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'email', :by => 'DESC' %>
                    <% else %>
                      <%= link_to image_tag("arrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'email', :by => 'ASC' %>
                    <% end %>
                  </div>
                  <div class="dataheaddiv">
                    Country
                  </div>
                  <div class="dataheaddiv">
                    Locations
                  </div>
                  <div class="dataheaddiv" style="width:100px">
                    Status
                  </div>
                </div>
                <% i = 0 %>
                <% @employees.each do |employee|  %>
                  <div class="datahead" style="background-color: <%= cycle("#cce9ed","#f0f8fa") %>">
                    <div class="datarowoptions">
                      <input type="checkbox" name="employee_ids[]" id="employee_<%= i %>" value="<%= employee.id %>"/>
                    </div>

                    <div class="dataheaddivwhite" style="width:110px ; padding-left: 3px">
                      <%= link_to employee.name,employee_path(employee)%>
                    </div>
                     <div class="dataheaddivwhite" style="width:170px">
                      <%=  employee.services.empty? ? "None" : employee.services.map{|r| [r.service_name]}.join(" , ") %>
                    </div>
                    <div class="databellowdiv" style="width:170px">
                      <%= employee.email.nil? ? "Unknown" : employee.email %>
                    </div>
                    <div class="dataheaddivwhite">
                      <%= employee.country.nil? ? "Unknown" : employee.country %>
                    </div>
                    <div class="databellowdiv">
                      <%= employee.locations.empty? ? "Unknown" : employee.locations.map{|r| [r.name]}.join(', ') %>
                    </div>
                    <div class="databellowdiv" style="width:100px">
                      <div id="status_<%= employee.id %>"></div>
                      <%= select_tag :status, options_for_select([['Active', 'Active'], ['Inactive', 'Inactive']],  employee.status), :onchange => "update_employee_status('#{employee.id }', this.value)"  %>
                    </div>
                  </div>
                  <% i += 1 %>
                <% end %>
              </div>
              <div style="clear: both; height: 10px"></div>
              <div class="pagination">
                <%= will_paginate @employees  %>
              </div>
              <div style="clear: both; height: 10px"></div>
              <%= submit_tag 'Delete', :onclick => "return validate_employees_to_delete(#{@employees.length})" , :class => "input_button" %>
            <% end %>
          </div>
        </div>
        <div class="midbgright"></div>
      </div>
    </div>
  </div>
  <div class="rightcontentgradient"></div>
</div>

app/views/employees/new.html.erb
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<div class="contentmiddle">
  <div class="leftcontentgradient"></div>
  <div class="centercontentgradient">
    <div id="guestmain">
      <%= render 'shared/employee_sub_tab' %>
      <div class="midbgrepeat">
        <div class="midbgleft"></div>
        <div class="midcontent">
          <%= render "/shared/side_bar" %>
          <div class="midright">
            <table >
              <tr>
                <td width="20%">
                  <table>
                    <tr>
                      <td colspan="6">
                        <b>  Name: </b>  <%=  @employee.name.nil? ? "Unknown" : @employee.name %> &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp;
                      </td>
                    </tr >
                    <tr>
                        <%= image_tag @employee.avatar.url(:thumb) %>
                    </tr>
                    <tr>
                      <td colspan="2">
                        <b> Email: </b><%=   @employee.email.nil? ? "Unknown" :  @employee.email %>
                      </td>
                    </tr>
                    <tr>
                      <td colspan="2">
                        <b> Country : </b> <%=   @employee.country.nil? ? "Unknown" : @employee.country  %>
                      </td>
                    </tr>
                    <tr>
                      <td colspan="3">
                        <b>Status : </b><%= @employee.status.nil? ? "Unknown" : @employee.status  %>
                      </td>
                    </tr>
                    <tr>
                      <td >
                        <%= button_to_function 'Edit' ,  "window.location.href= '#{edit_employee_path(@employee)}'", :class => 'input_button' %>
                      </td>
                      <td>
                        <%= button_to_function 'Back', "window.location.href= '#{employees_path}'", :class => 'input_button' %>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <div style="padding-left: 80%" >
              <%=  button_to_function 'Apply Leave' ,  "window.location.href= '#{new_employee_leave_application_path(@employee.id)}'", :class => 'input_button' %>
            </div>
            <div class="data">
              <div class="datahead">
                <div class="dataheaddiv"  style="width:150px" >
                  From Date
                </div>
                <div class="dataheaddiv"  style="width:150px">
                  To Date
                </div>
                <div class="dataheaddiv"  style="width:150px">
                  Type of Leave
                </div>
                <div class="dataheaddiv"  style="width:150px">
                  Leave Status
                </div>
                <div class="dataheaddiv"  style="width:240px">
                  Options
                </div>
              </div>
              <% @leave_applications.each do |leave_application| %>
                <div class="datahead"  style="background-color: <%= cycle("#cce9ed","#f0f8fa") %>">
                  <div class="dataheaddivwhite" style="width:150px" >
                    <%= leave_application.from.nil? ? "Unknown" : leave_application.from  %>
                  </div>
                  <div class="dataheaddivwhite" style="width:150px">
                    <%= leave_application.to.nil? ? "Unknown" : leave_application.to %>
                  </div>
                  <div class="databellowdiv" style="width:150px">
                    <%= leave_application.type_of_leave.nil? ? "Unknown" : leave_application.type_of_leave  %>
                  </div>
                  <div class="dataheaddivwhite"  style="width:150px">
                    <%= leave_application.leave_approval == "pending_approval" ? "Pending approval" : leave_application.leave_approval.capitalize %>
                  </div>
                  <div class="databellowdiv"  style="width:240px">
                    <%= link_to image_tag("edit.gif", :border => "0px"), edit_employee_leave_application_path(@employee.id,leave_application) %>
                    <%= link_to image_tag("no.gif", :border => "0px"), employee_leave_application_path(@employee.id,leave_application), :confirm => "Are you sure?", :method=>:delete %>
                  </div>
                </div>
              <%end%>
            </div>
          </div>
        </div>
        <div class="midbgright"></div>
      </div>
    </div>
  </div>
  <div class="rightcontentgradient"></div>
</div>