config/routes.rb
Spabooker::Application.routes.draw do

  
  

  resources :manage_leaves do
    member do
      put :update_status
    end

    collection do
      delete 'delete_selected'
    end
  end

  get "payments/index"

  get "hr_system/index"

  resources :payments do
    member do
      get "update_service_packages"
      put :update_status
    end

    collection do
      get "cash_register"
      post "new_entry"
      get 'search_cash_register'
    end

  end
  resources :gift_vouchers

    

  resources :sub_categories

  resources :payments

  resources :categories do
    member do
      post "add_sub_category"
      delete "delete_sub_category"
      get 'get_sub_categories'
    end
  end

  resources :services do
    member do
      get 'update_service_rates'
      delete "delete_selected_option"
    end

    collection do
      delete 'delete_selected'
      post "search"
    end
  end

  

  root :to => "guests#index"
  get "users/new"

 
  resources :appointments do
    collection do
      get 'appointments_by_date'
    end

    collection do
      get 'calendar'
      post "search"
    end

    member do
      get 'invoice'
      get 'print_invoice'
      post 'appointment_payment'
    end

  end

  resources :guests do
    member do
      put :update_status
      put :update_custom_field
      delete :destroy_custom_field
      get :appointments
      get :notes
      post :create_note
      delete :delete_note
      put :update_field
      get :purchases
    end
    collection do
      delete 'delete_selected'
      post 'csv_import'
      get 'csv_guest_form'
      get 'search'
      get :export_to_xls
      get :export_to_csv
      get :export_pdf
      get 'filter_guest'
      get :custom_fields
      post :create_custom_field
      post :change_custom_field_name
      post :change_custom_field_type
      get 'get_empty_csv'
      get 'guest_custom_field'
      
    end
  end

  resources  :events do
    member do
      post 'resize'
      post 'move'
    end

    collection do
      get 'get_events'
    end
  end

  resources :roles do
    collection do
      delete 'delete_selected'
      get 'search'
    
    end

    member do
      put :update_status
      put 'assign_permission'
    end
  end

  resources :permissions

  resources :user_sessions

  resources :users do
    collection do
      get 'manage_role'
      get 'new_user'
      post 'create_user'
    end

  
    member do
      put :update_name
    end
  end
  
  resources :packages do
    member do
      put :update_status
   
    end
    collection do
      delete 'delete_selected'
      post 'search'
    end
  end

  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  resources :locations do
    collection do
      delete 'delete_selected'
      post 'search'
      get 'get_outlets'
    end
    member do
      put :update_status
      get :get_operation_hours
      post :create_operation_hours
      get :show_operation_hours_on_date
      put :update_operation_time
      get :closed_dates
      get :new_closed_date
      post :add_closed_date
      get :edit_closed_date
      put :update_closed_date
      delete :delete_closed_date
    end
  end

  resources :equipments do
    collection do
      delete 'delete_selected'
      post 'search'
      put 'update_location_equipment_status'
    end
    member do
      put :update_status
    end
  end

  resources :employees do
    resources :leave_applications
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put "update_status"
      get :assign_role
    end
  end

  resources :rooms do
    collection do
      delete 'delete_selected'
      post 'search'
      
    end
    member do
      put :update_status
    end
  end

  resources :taxtypes do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    end
  end

  resources :memberships do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    end

  end

  resources :products do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    
      get "update_sub_categorie_products"
    end
    resources :inventories
  end

  resources :profiles do

    collection do
      delete 'delete_selected'
      post 'csv_import'
      get 'csv_profile_form'
      get :export_to_csv
      get :export_to_xls
      get :export_pdf
      post 'search'
      get 'get_empty_csv'
    end
    member do
      put :update_status
    end
  end

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'signup' => "users#new", :as=>:signup
  match 'account' => "users#account", :as=>:account
  match 'activate/:activation_code' => "users#activate", :as =>:activate

  
  

end

app/views/shared/_appointment_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Calendar", :class => (params[:action] == 'appointments_by_date' ? 'selected_subtab' :  'guestlink') %>
  </div>
  <div class="guesttoplinks">
    <%= link_to "Find Appointment", appointments_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink')%>
  </div>
  <div class="guesttoplinks">
    <%=link_to "Book Class", :class => 'guestlink' %>
  </div>
</div>

app/views/shared/_employee_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Employees",  employees_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
 
</div>

app/views/shared/_equipment_sub_tab.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Equipments", equipments_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
</div>

app/views/shared/_guest_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Guests", guests_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
<%#*<div class="guesttoplinks">%>
<%#= link_to "Find Duplicates", guests_path, :class => ((params[:action] == 'find_duplicates') ? 'selected_subtab' : 'guestlink') %>
<%#*</div>%>
  <div class="guesttoplinks">
    <%=link_to "Custom Fields", custom_fields_guests_path, :class => ((params[:action] == 'custom_fields') ? 'selected_subtab' : 'guestlink') %>
  </div>
</div>

app/views/shared/_package_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Packages", packages_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
 
</div>

app/views/shared/_payment_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Payments", payments_path, :class => (params[:controller] == 'payments' ? 'selected_subtab' : 'guestlink') %>
  </div>
  <div class="guesttoplinks">
    <%= link_to "Gift Vouchers", gift_vouchers_path, :class =>  (params[:controller] == 'gift_vouchers' ? 'selected_subtab' : 'guestlink') %>
  </div>
  <div class="guesttoplinks">
    <%= link_to "Cash Register", cash_register_payments_path, :class =>  ((params[:controller] == 'payments' and (params[:action] == 'cash_register' or params[:action] == 'new_entry')) ? 'selected_subtab' : 'guestlink') %>
  </div>
</div>

app/views/shared/_permission_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Permissions", permissions_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
  

</div>

app/views/shared/_product_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Products", products_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
  
</div>

app/views/shared/_profile_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Profiles", profiles_path,  :class => (((params[:controller] == 'profiles') and (params[:action] == 'index' or params[:action] == 'search' or params[:action] == 'new' or params[:action] == 'create' or params[:action] == 'show')) ? 'selected_subtab' : 'guestlink')%>
  </div>
  <div class="guesttoplinks">
    <%= link_to "Manage Leaves", leave_applications_path, :class =>  'guestlink' %>
  </div>
</div>

app/views/shared/_role_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Roles",  roles_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
</div>

app/views/shared/_room_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Rooms",  rooms_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
</div>

app/views/shared/_search_appointment.html.erb
<div class="midleft">
  <div class="searchimg">
    SEARCH GUEST LIST
  </div>
  <div class="midbgsearchrepeat">
    <div class="guest">Appointments
      <div>
        <div>
          <%= form_tag(search_appointments_path, :method=>'post', :multipart => true) do %>
            <p> Name : <%= text_field_tag "name", params[:name] %> </p>
            <p> Email : <%= text_field_tag "email", params[:email] %></p>
            <p>Billing Phone  Number : <%= text_field_tag "phone", params[:phone] %></p>
            <p>Status : <%= select_tag :status,  options_for_select(["Active" ,"Inactive"],params[:status])  %></p>
            <p>Records per page : <%= select_tag :records_per_page,  options_for_select([10, 20, 30, 50],params[:records_per_page])  %></p>
            <p></p>
            <p> <%= submit_tag 'Submit' %> </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="midleftbottom"></div>
</div>

app/views/shared/_service_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Services",    services_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
</div>

app/views/shared/_taxtype_sub_tab.html.erb
<div class="guesttop">
  <div class="guesttoplinks">
    <%= link_to "Manage Taxtype",  taxtypes_path, :class => ((params[:action] == 'index' or params[:action] == 'search') ? 'selected_subtab' : 'guestlink') %>
  </div>
</div>