config/routes.rb
Spabooker::Application.routes.draw do

  
  

  resources :manage_leaves do
    member do
      put :update_status
    end

    collection do
      delete 'delete_selected'
    end
  end

  get "payments/index"

  get "hr_system/index"

  resources :payments do
    member do
      get "update_service_packages"
      put :update_status
    end

    collection do
      get "cash_register"
      post "new_entry"
      get 'search_cash_register'
    end

  end
  resources :gift_vouchers

    

  resources :sub_categories

  resources :payments

  resources :categories do
    member do
      post "add_sub_category"
      delete "delete_sub_category"
      get 'get_sub_categories'
    end
  end

  resources :services do
    member do
      get 'update_service_rates'
      delete "delete_selected_option"
    end

    collection do
      delete 'delete_selected'
      post "search"
    end
  end

  

  root :to => "guests#index"
  get "users/new"

 
  resources :appointments do
    collection do
      get 'appointments_by_date'
    end

    collection do
      get 'calendar'
      post "search"
    end

    member do
      get 'invoice'
      get 'print_invoice'
      post 'appointment_payment'
    end

  end

  resources :guests do
    member do
      put :update_status
      put :update_custom_field
      delete :destroy_custom_field
      get :appointments
      get :notes
      post :create_note
      delete :delete_note
      put :update_field
      get :purchases
    end
    collection do
      delete 'delete_selected'
      post 'csv_import'
      get 'csv_guest_form'
      get 'search'
      get :export_to_xls
      get :export_to_csv
      get :export_pdf
      get 'filter_guest'
      get :custom_fields
      post :create_custom_field
      post :change_custom_field_name
      post :change_custom_field_type
      get 'get_empty_csv'
      get 'guest_custom_field'
      
    end
  end

  resources  :events do
    member do
      post 'resize'
      post 'move'
    end

    collection do
      get 'get_events'
    end
  end

  resources :roles do
    collection do
      delete 'delete_selected'
      get 'search'
    
    end

    member do
      put :update_status
      put 'assign_permission'
    end
  end

  resources :permissions

  resources :user_sessions

  resources :users do
    collection do
      get 'manage_role'
      get 'new_user'
      post 'create_user'
    end

  
    member do
      put :update_name
    end
  end
  
  resources :packages do
    member do
      put :update_status
   
    end
    collection do
      delete 'delete_selected'
      post 'search'
    end
  end

  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  resources :locations do
    collection do
      delete 'delete_selected'
      post 'search'
      get 'get_outlets'
    end
    member do
      put :update_status
      get :get_operation_hours
      post :create_operation_hours
      get :show_operation_hours_on_date
      put :update_operation_time
      get :closed_dates
      get :new_closed_date
      post :add_closed_date
      get :edit_closed_date
      put :update_closed_date
      delete :delete_closed_date
    end
  end

  resources :equipments do
    collection do
      delete 'delete_selected'
      post 'search'
      put 'update_location_equipment_status'
    end
    member do
      put :update_status
    end
  end

  resources :employees do
    resources :leave_applications
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put "update_status"
      get :assign_role
    end
  end

  resources :rooms do
    collection do
      delete 'delete_selected'
      post 'search'
      
    end
    member do
      put :update_status
    end
  end

  resources :taxtypes do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    end
  end

  resources :memberships do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    end

  end

  resources :products do
    collection do
      delete 'delete_selected'
      post 'search'
    end
    member do
      put :update_status
    
      get "update_sub_categorie_products"
    end
    resources :inventories
  end

  resources :profiles do

    collection do
      delete 'delete_selected'
      post 'csv_import'
      get 'csv_profile_form'
      get :export_to_csv
      get :export_to_xls
      get :export_pdf
      post 'search'
      get 'get_empty_csv'
    end
    member do
      put :update_status
    end
  end

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'signup' => "users#new", :as=>:signup
  match 'account' => "users#account", :as=>:account
  match 'activate/:activation_code' => "users#activate", :as =>:activate

  
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "100x100>" }

  validates :status, :name, :sales_tax, :presence => true
  validates :category_id, :presence => { :message => "Please slect one category"}
  validates :sub_category_id, :presence => { :message => "Please slect one sub category"}
  validates :name, :uniqueness => true
  validates :sales_tax, :quantity, :numericality => true

  has_many :payment_products, :dependent => :destroy
  has_many :payments, :through => :payment_products
  
  has_many :inventories, :dependent => :destroy
  belongs_to :category, :foreign_key => 'category_id'
  belongs_to :sub_category, :foreign_key => 'sub_category_id'
  belongs_to :product_brand, :foreign_key => 'product_brand_id'

  has_many :products_services, :dependent => :destroy
  has_many :services, :through => :products_services

  has_many :locations_products, :dependent => :destroy
  has_many :locations, :through => :locations_products


  define_index do
    indexes name, :sortable => true
    indexes status, :status => true
    #    indexes location, :sortable => true
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :service_name, :category_id, :sub_category_id, :duration, :staff_recovery_time, :room_recovery_time, :book_online, :rate,:equipment,:special_notes, :status, :service_code, :requires_equipment
  attr_accessor :service_ids, :room_ids, :equipment_ids, :service_id, :employee_id, :room_id, :equipment_id
  belongs_to :category
  belongs_to :sub_category
  has_many :appointments
  has_many :membership_services, :dependent => :destroy
  has_many :memberships , :through => :membership_services

  has_many :package_services, :dependent => :destroy
  has_many :packages, :through => :package_services


  has_many :payment_services, :dependent => :destroy
  has_many :payments, :through => :payment_services

  has_many :room_services, :dependent => :destroy
  has_many :rooms, :through => :room_services

  has_many :employee_services, :dependent => :destroy
  has_many :employees, :through => :employee_services


  has_many :equipments_services, :dependent => :destroy
  has_many :equipments, :through => :equipments_services

  has_many :products_services, :dependent => :destroy
  has_many :products, :through => :products_services
  
  define_index do
    indexes service_name, :sortable => true
    indexes duration, :sortable => true
    indexes rate, :sortable => true
    indexes status, :sortable => true
  end

  

  validates :service_name, :category_id, :sub_category_id, :duration, :book_online, :status, :service_code , :presence => true
  validates_length_of :service_name, :maximum => 200
  validates_length_of :rate, :maximum => 10
  validates_length_of :special_notes, :maximum => 250, :allow_blank => true
  validates_numericality_of :rate
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    per_page = params[:per_page] || 10
    params[:order] = params[:order] || 'name'
    params[:by] = params[:by] || 'ASC'
    @products = Product.paginate(:all,:page => params[:page] , :per_page=> per_page, :order => params[:order]+ ' '+params[:by])
  end

  def update_sub_categorie_products
    @sub_categories = SubCategory.find(:all, :conditions => ["category_id = #{params[:id]}"])
    options =""
    for sub_category in @sub_categories
      options += "<option value=#{sub_category.id}>#{sub_category.name}</option>"
    end
    render :update do |page|
      page.replace_html 'sub_categories', options
    end
  end

  def search
    per_page = params[:per_page] || 10
    @product_ids = []
    if !params[:name].to_s.blank?
      @product = Product.search_for_ids "*#{params[:name]}*"
      puts ">>>>>>>>>>>>>>"
      puts params[:name]
      @product_ids << @product if !@product.empty?
    end
    if !@product_ids.to_s.blank?
      @products = Product.find(@product_ids).paginate(:page => params[:page], :per_page => per_page)
    else
      flash[:error] = "Couldn't find any products with the search criteria."
      @products = [].paginate
    end
    render 'index'
  end
  
  def update_status
    @product = Product.find(params[:id])
    if @product and @product.update_attributes(:status => params[:status])
      message = "<span style='color: green'>Updated</span>"
    else
      message = "<span style='color: red'>Error</span>"
    end
    render :text => message

  end

  def delete_selected
    if !params[:product_ids].to_a.empty?
      for product_id in params[:product_ids]
        Product.find(product_id).update_attribute(:status, 'Deleted')
      end
      flash[:notice] = "Succcessfully deleted selected products."
    else
      flash[:error] = "Please select atleast one product to delete"
    end
    redirect_to products_path
  end

  def show
    @product = Product.find(params[:id])
    @inventories = @product.inventories
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    @product.status = 'Active'
    if @product.save
      flash[:notice] = "Succcessfully created a new product, please create the invertory for the product."
      redirect_to  new_product_inventory_path(@product.id)
    else
      flash[:error] = "Couldn't create the new product, plase try again."
      @sub_categories = SubCategory.all(:select => "id, name", :conditions => ["category_id = #{params[:product][:sub_category_id]}"]) if !params[:product][:sub_category_id].nil?
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
    @sub_categories = SubCategory.all
    @inventories = @product.inventories
  end

  def update
      
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      @product.category_id = params[:name][:category_id]
      @product.sub_category_id = params[:name][:sub_category_id]
      flash[:notice] = "Succcessfully updated product details."
      redirect_to products_path
    else
      flash[:error] = "Couldn't update product details, plase try again."
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.destroy(params[:id])
    flash[:notice] = "Successfully destroyed product."
    redirect_to products_path
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="contentmiddle">
  <div class="leftcontentgradient"></div>
  <div class="centercontentgradient">
    <div id="guestmain">
      <%= render 'shared/product_sub_tab' %>
      <div class="midbgrepeat">
        <div class="midbgleft"></div>
        <div class="midcontent">
          <%= render "/shared/side_bar" %>
          <div class="midright">
            <%= form_for @product do |f| %>
              <h3 style="color:#FFFFFF; padding-left:5%">New Product</h3>
              <table style="padding-left: 5%">
                <tr>
                  <td>Name</td>
                  <td><%= f.text_field :name, :size => '20x2' %>
                    <div style='color: red;'><%= validation_errors @product.errors['name'] %></div>
                  </td>
                </tr>
                <tr>
                  <td>Description</td>
                  <td><%= f.text_area :description,:size => '25x3' %>
                    <div style='color: red;'><%= validation_errors @product.errors['description'] %></div>
                  </td>
                </tr>
                <tr>
                  <td>Category</td>
                  <td>
                    <%= f.select :category_id, [["Select", ""]]+Category.all(:select => "id, name").map {|category| [category.name,category.id] }, {}, {:onchange => "get_sub_categorie_products(this.value)"} %>
                    <div style='color: red;'><%= validation_errors @product.errors['category_id'] %></div>
                  </td>
                </tr>

                <tr>
                  <td>Sub category</td>
                  <td>
                    <% selected_sub_category = @sub_categories || [] %>
                    <%= f.select :sub_category_id, selected_sub_category.map{|sub_category| [sub_category.name, sub_category.id]}, {}, {:id => "sub_categories"} %>
                    <div style='color: red;'><%= validation_errors @product.errors['sub_category_id'] %></div>
                  </td>
                </tr>

                <tr>
                  <td>Brand</td>
                  <% @product_brands =  ProductBrand.all %>
                  <td><%= f.select :product_brand_id, @product_brands.map {|r| [r.product_brand,r.id] } %></td>
                </tr>

                <tr>
                  <td>Photo</td>
                  <td><%= f.file_field :avatar,:size => '20x2' %></td>
                </tr>
                <tr>
                  <td>Ingredients</td>
                  <td><%= f.text_area :ingredients, :size => '25x3' %>
                  </td>
                </tr>

                <tr>
                  <td>Sales Tax</td>
                  <td><%= f.text_field :sales_tax, :size => '20x2'%>
                    <div style='color: red;'><%= validation_errors @product.errors['sales_tax'] %></div>
                  </td>
                </tr>

                <tr>
                  <td>Quantity</td>
                  <td><%= f.text_field :quantity, :size => '20x2'%>
                    <div style='color: red;'><%= validation_errors @product.errors['quantity'] %></div>
                  </td>
                </tr>

                <tr>
                  <td>Online Shop</td>
                  <td><%= f.text_field :online_shop, :size => '20x2'%>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td><%= f.submit @product.new_record? ? "Create"  : "Update", :class => 'input_button' %>
                    <%= button_to_function 'Cancel', "window.location.href= '#{products_path}'", :class => 'input_button' %>
                  </td>
                </tr>
              </table>
            <% end %>
          </div>
        </div>
        <div class="midbgright"></div>
      </div>
    </div>
  </div>
  <div class="rightcontentgradient"></div>
</div>

app/views/products/edit.html.erb
<%= render  'form' %>

app/views/products/index.html.erb
<div class="contentmiddle">
  <div class="leftcontentgradient"></div>
  <div class="centercontentgradient">
    <div id="guestmain">
      <%= render 'shared/product_sub_tab' %>
      <div class="midbgrepeat">
        <div class="midbgleft"></div>
        <div class="midcontent">
          <%= render "/shared/side_bar" %>
          <div class="midright">
            <div class="midrighttop">
              <div class="midrighttopleft"></div>
              <div class="midrighttopcenter">
                <div class="midrighttoplinks">
                  <div style="float:right">
                    <div class="midrighttoplinkdiv">
                      <%= link_to "New Product" ,   new_product_path,  :class => 'midrighttoplink'%>
                    </div>
                  </div>
                </div>
              </div>
              <div class="midrighttopright"></div>
            </div>

            <div class="dataheaddiv" style="width:850px; text-align: left; border: 0; font-weight: bold;" >
              Search Criteria
            </div>
            <div class="search_tab_right">
              <%= form_tag(search_products_path, :method=>'post', :multipart => true) do %>
                Name :<%= text_field_tag "name", params[:name] %>
                Status : <%= select_tag :status,  options_for_select(["Active" ,"Inactive"],params[:status])  %>
                <%= submit_tag 'Search', :class => "input_button"%>
              <%end%>
            </div>

            <%= form_tag   delete_selected_products_path, :method => :delete do %>
              <div class="data" >
                <div class="datahead">
                  <div class="dataheaddiv" style="width: 100%; text-align: left; border: 0">
                    <%= select_tag :per_page, options_for_select([10, 20, 30, 50], params[:per_page]), :onchange => "reload_with_new_param('per_page', this.value)"  %>
                  </div>

                </div>
                <div class="datahead">
                  <div class="dataheadoptions">
                    <input type="checkbox" id="total_products" onclick="select_all_products(<%= @products.length %>)"/>
                  </div>
                  <div class="dataheaddiv" style="width:300px;padding-left: 3px">
                    Name
                    <% if params[:by] == 'ASC' %>
                      <%= link_to image_tag("uparrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'name', :by => 'DESC' %>
                    <% else %>
                      <%= link_to image_tag("arrow.gif", :width => "8", :height => "9", :border => "0"), :action => 'index', :order => 'name', :by => 'ASC' %>
                    <% end %>
                  </div>
                  <div class="dataheaddiv" style="width:220px" >
                    Category
                  </div>
                  <div class="dataheaddiv" style="width:270px">
                    Status
                  </div>
                </div>
                <% i = 0 %>
                <% @products.each do |product|  %>
                  <div class="datahead" style="background-color: <%= cycle("#cce9ed","#f0f8fa") %>">
                    <div class="datarowoptions">
                      <input type="checkbox" name="product_ids[]" id="product_<%= i %>" value="<%= product.id %>"/>
                    </div>

                    <div class="dataheaddivwhite" style="width:300px; padding-left: 7px">
                      <%= link_to product.name,product_path(product)%>
                    </div>
                    <div class="databellowdiv" style="width:220px">
                      <%= product.category.nil? ? "Unknown" : product.category.name  %>
                    </div>

                    <div class="databellowdiv" style="width:270px">
                      <div id="status_<%= product.id %>"></div>
                      <%= select_tag :status, options_for_select([['Active', 'Active'], ['Inactive', 'Inactive']],  product.status), :onchange => "update_product_status('#{product.id }', this.value)"  %>
                    </div>
                  </div>
                  <% i += 1 %>
                <% end %>
              </div>
              <div style="clear: both; height: 10px"></div>
              <div class="pagination">
                <%= will_paginate @products  %>
              </div>
              <div style="clear: both; height: 10px"></div>
              <%= submit_tag 'Delete', :onclick => "return validate_products_to_delete(#{@products.length})", :class => 'input_button'  %>
            <% end %>
          </div>
        </div>
        <div class="midbgright"></div>
      </div>
    </div>
  </div>
  <div class="rightcontentgradient"></div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class="contentmiddle">
  <div class="leftcontentgradient"></div>
  <div class="centercontentgradient">
    <div id="guestmain">
      <%= render 'shared/product_sub_tab' %>
      <div class="midbgrepeat">
        <div class="midbgleft"></div>
        <div class="midcontent">
          <%= render '/shared/side_bar' %>
          <div class="midright">
            <table>
              <tr align="left">
                <td colspan="5">
                  <b>  Name: </b>  <%= @product.name %>   
                </td>
              </tr >
              <tr>
                <td colspan="2">
                  <b> Category: </b><%=@product.category.name %>
                </td>
              </tr>

              <tr>
                <td colspan="3">
                  <b>Status : </b><%= @product.status%>
                </td>
              </tr>
              <tr>
                <td colspan="3">
                  <%= button_to_function 'Edit' ,  "window.location.href= '#{edit_product_path(@product)}'", :class => 'input_button' %>
                  <%= button_to_function 'Cancel', "window.location.href= '#{products_path}'", :class => 'input_button' %>
                  
                </td>
                <td style="padding-left: 100%">
                  <%=  button_to_function 'New Inventory' ,  "window.location.href= '#{ new_product_inventory_path(@product.id)}'", :class => 'input_button' %>
                </td>
              </tr>
            </table>
            <div class="data">
              <div class="datahead">
                <div class="dataheaddiv"  style="width:150px; " >
                  Inventory Name
                </div>
                <div class="dataheaddiv"  style="width:150px">
                  Barcode
                </div>
                <div class="dataheaddiv"  style="width:100px">
                  Retail Price
                </div>
                <div class="dataheaddiv"  style="width:100px">
                  Cost Price
                </div>
                <div class="dataheaddiv"  style="width:150px">
                  Stock Balance
                </div>

                <div class="dataheaddiv"  style="width:190px">
                  Actions
                </div>
              </div>
              <% @inventories.each do |inventory| %>
                <div class="datahead"  style="background-color: <%= cycle("#cce9ed","#f0f8fa") %>">
                  <div class="dataheaddivwhite" style="width:150px; padding-left: 5px" >
                    <%= inventory.name %>
                  </div>
                  <div class="dataheaddivwhite" style="width:150px">
                    <%= inventory.barcode %>
                  </div>
                  <div class="databellowdiv" style="width:100px">
                    <%= inventory.retail_price %>
                  </div>
                  <div class="dataheaddivwhite"  style="width:100px">
                    <%= inventory.cost_price %>
                  </div>
                  <div class="dataheaddivwhite"  style="width:150px">
                    <%= inventory.stock_balance %>
                  </div>
                  <div class="databellowdiv"  style="width:190px; padding-left: 1px">
                    <%= link_to "Edit", edit_product_inventory_path(@product.id,inventory) %>
                    <%= link_to 'Delete',  product_inventory_path(@product.id, inventory), :confirm => "Are you sure?", :method=>:delete %>
                  </div>
                </div>
              <%end%>
            </div>


          </div>
        </div>
        <div class="midbgright"></div>
      </div>
    </div>
  </div>
  <div class="rightcontentgradient"></div>
</div>